### ISSUE TITLE
Not an issue again

### ISSUE THREAD

**Issue by EL86** [Zbomb2000/ANTIxl#10]
This is not an issue, I just don't know a better way to contact you. Once your done with the beta I would be happy to try it out on random IXL's and see how it works. Hope it's done soon!

**Comment by Zbomb2000** [comment]
### @EL86

> Once your done with the beta I would be happy to try it out on random IXL's and see how it works.

**Ok, thanks!**

> This is not an issue, I just don't know a better way to contact you.

**I have my email at the bottom of the README file. It's "hxl9500@gmail.com" (I don't check my inbox that often).**

---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I won't be done with the beta version for probably until the end of this school year, or possibly into next school year. I'm the only person working on this, and this is a pretty big project. I'm gonna try to get my cousin to help me with the image processing stuff because he knows way more Python than me.

---

### Other stuff:

- [README.md/ContactInformation](https://github.com/Zbomb2000/ANTIxl/blob/main/README.md#contact-information)
